# Generated by Django 3.1.4 on 2020-12-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adr', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField(default=0)),
                ('exec_date', models.DateTimeField(verbose_name="La date d'executions du ping")),
                ('ip_adr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ping.network')),
            ],
        ),
    ]
