# Generated by Django 3.1.4 on 2020-12-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0002_auto_20201224_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='State',
            field=models.CharField(choices=[('On', 'Off')], max_length=3),
        ),
    ]
