# Generated by Django 3.1.4 on 2020-12-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_auto_20201224_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='State',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='exec_date',
            field=models.DateTimeField(verbose_name="Date d'execution du ping"),
        ),
    ]
