# Generated by Django 3.1.4 on 2020-12-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0005_auto_20201224_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='State',
            field=models.CharField(choices=[('ON', 'Active'), ('OFF', 'Not Active'), ('??', 'Who know')], max_length=20, verbose_name='Etat du network'),
        ),
    ]
