# Generated by Django 3.1.4 on 2020-12-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0008_auto_20201225_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='State',
            field=models.BooleanField(default=False, help_text='True Means ON', verbose_name='Etat du network'),
        ),
    ]
