# Generated by Django 3.1.4 on 2020-12-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0009_auto_20201225_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='ip_adr',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='Adresse IP'),
        ),
    ]
