# Generated by Django 2.0.5 on 2021-01-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0010_auto_20201225_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name_plural': 'Les serveurs'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': "L'état des servers"},
        ),
    ]
